services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tpDb
    ports:
      - "5432:5432"
    volumes:
    - type: bind
      source: ./VolumenBaseDatos1
      target: /var/lib/postgresql/data
      bind:
        create_host_path: true
    - type: bind
      source: ./tablas
      target: /docker-entrypoint-initdb.d
      bind:
        create_host_path: true
